/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpgenius;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author alber
 */
public class Principal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        verde.addActionListener(this);
        vermelho.addActionListener(this);
        amarelo.addActionListener(this);
        azul.addActionListener(this);
        iniciarParar.addActionListener(this);
//        verde.setEnabled(false);
//        vermelho.setEnabled(false);
//        azul.setEnabled(false);
//        amarelo.setEnabled(false);
//        label.setVisible(false);
//        tempoTexto.setVisible(false);
//        tempo.setVisible(false);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vermelho = new javax.swing.JButton();
        amarelo = new javax.swing.JButton();
        azul = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        verde = new javax.swing.JButton();
        tempoTexto = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        tempo = new javax.swing.JLabel();
        txtRodada = new javax.swing.JLabel();
        iniciarParar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        vermelho.setBackground(new java.awt.Color(255, 0, 0));
        vermelho.setPreferredSize(new java.awt.Dimension(200, 100));

        amarelo.setBackground(new java.awt.Color(255, 255, 0));
        amarelo.setPreferredSize(new java.awt.Dimension(200, 100));

        azul.setBackground(new java.awt.Color(0, 0, 255));
        azul.setPreferredSize(new java.awt.Dimension(200, 100));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        titulo.setText("Genius");

        verde.setBackground(new java.awt.Color(0, 255, 0));
        verde.setPreferredSize(new java.awt.Dimension(200, 100));

        tempoTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tempoTexto.setText("Tempo:");

        label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label.setText("Rodada:");

        tempo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtRodada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        iniciarParar.setBackground(new java.awt.Color(153, 153, 153));
        iniciarParar.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amarelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtRodada)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vermelho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tempoTexto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tempo)
                                        .addGap(50, 50, 50))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iniciarParar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iniciarParar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempoTexto)
                    .addComponent(tempo)
                    .addComponent(label)
                    .addComponent(txtRodada))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amarelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//instância um objeto da classe Random usando o construtor padrão
    Random gerador = new Random();
    int cont;
    int cores[];
    ArrayList<Integer> clique;
    boolean erro;
    boolean piscando;

    public void init() {
        cont = 1;
        cores = new int[8];
        clique = new ArrayList<>();
        erro = false;
        piscando = false;
        for (int i = 0; i < 8; i++) {
            cores[i] = gerador.nextInt(4) + 1;
        }
        iniciarParar.setEnabled(true);
        iniciarParar.setText("Iniciar");
        tempo.setText("5s");
        txtRodada.setText("1");
        disable();
    }

    public void disable() {
        verde.setEnabled(false);
        azul.setEnabled(false);
        vermelho.setEnabled(false);
        amarelo.setEnabled(false);
        //verde.setEnabled(false);
    }

    public void enable() {
        verde.setEnabled(true);
        vermelho.setEnabled(true);
        amarelo.setEnabled(true);
        azul.setEnabled(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        iniciarParar.setEnabled(false);
        if (e.getSource() == iniciarParar) {
            piscando = true;
            Thread rodada = new Thread() {
                public double time = 5.0;

                public void run() {
                    try {
                        Timer timer = new Timer(50, new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                time -= 0.051;
                                tempo.setText(String.format("%.2fs", time));
                            }
                        });
                        tempo.setText("5s");
                        txtRodada.setText(String.valueOf(cont));
                        for (int i = 0; i < cont; i++) {
                            new AcaoT(cores[i]).join();
                        }
                        clique.clear();
                        piscando = false;
                        enable();
                        timer.start();
                        sleep(5000);
                        timer.stop();
                        for (int i = 0; i < cont; i++) {
                            if (clique.isEmpty()) {
                                erro = true;
                            } else if (cores[i] != clique.get(i)) {
                                erro = true;
                            }
                        }
                        time = 0;
                        tempo.setText(String.format("%.2fs", time));
                        disable();
                        cont++;
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    if (erro) {
                        init();
                        JOptionPane.showMessageDialog(null, "Você errou!");
                    } else if (cont == 9) {
                        init();
                        JOptionPane.showMessageDialog(null, "Você VENCEEEEU!");
                    } else {
                        disable();
                        iniciarParar.setEnabled(true);
                        iniciarParar.setText("Continuar");
                    }
                }
            };
            rodada.start();
        } else if (e.getSource() == verde && !piscando) {
            clique.add(1);

            if (cont == clique.size()) {
                disable();
            }

        } else if (e.getSource() == vermelho && !piscando) {
            clique.add(2);
            if (cont == clique.size()) {
                disable();
            }
        } else if (e.getSource() == amarelo && !piscando) {
            clique.add(3);
            if (cont == clique.size()) {
                disable();
            }
        } else if (e.getSource() == azul && !piscando) {
            clique.add(4);
            if (cont == clique.size()) {
                disable();
            }
        } else {
            disable();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JButton amarelo;
    protected static javax.swing.JButton azul;
    private javax.swing.JButton iniciarParar;
    protected static javax.swing.JLabel label;
    private javax.swing.JLabel tempo;
    private javax.swing.JLabel tempoTexto;
    private javax.swing.JLabel titulo;
    protected static javax.swing.JLabel txtRodada;
    protected static javax.swing.JButton verde;
    protected static javax.swing.JButton vermelho;
    // End of variables declaration//GEN-END:variables
}
